### ISSUE TITLE
Jolla Maps is missing in Store

### ISSUE THREAD

**Issue by isgursoy** [CancroSailors/droid-config-cancro#11]
Is it because of legal reasons?

**Comment by Nokius** [comment]
@isgursoy sorry this is not a bug :)

Jolla Maps (sailfish-maps) is proprietary/commercial package

**Comment by saidinesh5** [comment]
@Nokius I think maps is an important application, So we should pre install poor  maps with the next build.

**Comment by Nokius** [comment]
@saidinesh5 yes I open for 3rd-part maps :)

**Comment by saidinesh5** [comment]
https://github.com/CancroSailors/sailfish-build-environment/commit/de3d612d241e1235c51ae0ddbe320eb1ec5731eb

Added
