### ISSUE TITLE
[jolla-ui-configuration-cancro.yaml] missing pakages

### ISSUE THREAD

**Issue by Nokius** [CancroSailors/droid-config-cancro#6]
Introduced starting Sailfish OS 2.0.4.x:
3rd party accounts like Twitter, VK, cloud services, etc
jolla-settings-accounts-extensions-3rd-party-all

**Comment by saidinesh5** [comment]
https://github.com/CancroSailors/droid-config-cancro/commit/e80d21aa64e07946267eb2da3e86cd310372e789


Fixed it
