### ISSUE TITLE
Low camera resolution for Jolla Camera App

### ISSUE THREAD

**Issue by isgursoy** [CancroSailors/droid-config-cancro#7]
Resolution is 2MP for the front camera, and the rear cam is 8MP.
@saidinesh5 stated that "Right now there is a bug in the camera app , that's resetting the viewfinder resolution to an odd ratio. Maybe they both are related? Try out with a 3rd party camera app from warehouse/Jolla store."
That is right, Cameraplus working well but resulting image quality is poor compared to the stock app.

**Comment by Nokius** [comment]
@isgursoy can you please confirm that the picture has the correct resolution as [configured](https://github.com/CancroSailors/droid-config-cancro/commit/7d432d46bc4c226b0786fae0ccb351b21e19406d#diff-d965690dc9d8c0530fdc431e0e611010) Thanks

**Comment by isgursoy** [comment]
This is mine: 
_/etc/dconf/db/vendor.d/jolla-camera-hw.txt_
> [apps/jolla-camera/primary/image]
> imageResolution='4208x3120'
> videoResolution='1920x1080'
> **viewfinderResolution='1920x1080'**
> isoValues=[0, 100, 200, 400]
> whiteBalanceValues=[0, 3, 2, 6, 5]
> focusDistanceValues=[8, 4, 16]
> flashValues=[1, 2, 4]
> exposureCompensationValues=[4, 2, 0, -2, -4]
> imageResolution_4_3='4208x3120'
> imageResolution_16_9='4208x2368'
> viewfinderResolution_4_3='1440x1080'
> viewfinderResolution_16_9='1920x1080'
> resolutionText_4_3='camera_settings-me-4-3-8m'
> resolutionText_16_9='camera_settings-me-16-9-6m'
> focusDistance=16
> 
> [apps/jolla-camera/secondary/image]
> imageResolution='1600x1200'
> videoResolution='1920x1080'
> **viewfinderResolution='1920x1080'**
> isoValues=[0, 100, 200, 400]
> whiteBalanceValues=[0, 3, 2, 6, 5]
> focusDistanceValues=[4]
> flashValues=[2]
> exposureCompensationValues=[4, 2, 0, -2, -4]
> imageResolution_4_3='1600x1200'
> imageResolution_16_9='1920x1080'
> viewfinderResolution_4_3='1440x1080'
> viewfinderResolution_16_9='1920x1080'
> resolutionText_4_3='camera_settings-me-4-3-2m'
> resolutionText_16_9='camera_settings-me-16-9-1m'
> focusDistance=4
> 
> [apps/jolla-camera/primary/video]
> imageResolution='1920x1080'
> videoResolution='1920x1080'
> viewfinderResolution='1920x1080'
> isoValues=[0, 100, 200, 400]
> whiteBalanceValues=[0, 3, 2, 6, 5]
> focusDistanceValues=[4, 16]
> flashValues=[2, 32]
> exposureCompensationValues=[4, 2, 0, -2, -4]
> focusDistance=16
> 
> [apps/jolla-camera/secondary/video]
> imageResolution='1920x1080'
> videoResolution='1920x1080'
> viewfinderResolution='1920x1080'
> isoValues=[0, 100, 200, 400]
> whiteBalanceValues=[0, 3, 2, 6, 5]
> focusDistanceValues=[4]
> flashValues=[2]
> exposureCompensationValues=[4, 2, 0, -2, -4]
> focusDistance=4

Only bold viewfinderResolution's are different (1440x1080 in git). I changed it, reboot, and still same.

**Comment by Nokius** [comment]
@isgursoy  which build do you use?

**Comment by isgursoy** [comment]
uname: Linux Sailfish 3.4.0-cyanogenmod #34 SMP PREEMPT Fri Dec 23 19:08:28 UTC 2016 armv7l armv7l armv7l GNU/Linux

I got them here, a few days ago, after last update: https://forum.xda-developers.com/xiaomi-mi-3/orig-development/alpha-sailfishos-2-0-2-51-alpha-cancro-t3462419

**Comment by Nokius** [comment]
@isgursoy sorry wrong link it's correct https://github.com/CancroSailors/droid-config-cancro/commit/dbef2da0714c9bca9d5db4c1d73c1e38c2b4941d

**Comment by Nokius** [comment]
@isgursoy the taken image should have 4208x3120 as resolution

**Comment by isgursoy** [comment]
Yes and I noticed that it was already 4208x3120. But camera settings shows 8MP (before and now). My bad, sorry.

**Comment by Nokius** [comment]
@isgursoy ah then the bug is [here ](https://github.com/CancroSailors/droid-config-cancro/blob/master/sparse/etc/dconf/db/vendor.d/jolla-camera-hw.txt#L14)

**Comment by Nokius** [comment]
I will look into this issue Thanks for reporting 

* droid-camres and camera-settings-plugin
* is the correct Mpix set

**Comment by isgursoy** [comment]
Exactly.
I think secondary image resolution should be 8MP for mi4, right? It is 1600x1200 now.

**Comment by saidinesh5** [comment]
@isgursoy btw.  you need to run `dconf update` after making changes in the config file for them to be reflected. Simple reboot doesn't work.

**Comment by isgursoy** [comment]
Still same after dconf update. Front cam is 1600 and camera settings has not correct resolution.
