### ISSUE TITLE
3G and LTE does not work for mi4

### ISSUE THREAD

**Issue by isgursoy** [CancroSailors/droid-config-cancro#8]
I have -50 to -80 dBm signal. How can I collect backtrace to investigate that issue?
By the way I noticed that current release does not have csd. *#*#310#*#* or terminal "csd" do not work.

**Comment by Nokius** [comment]
@isgursoy Thanks for the report I will take look into

**Comment by isgursoy** [comment]
Thanks for your time.

**Comment by isgursoy** [comment]
Also, this buggy g drains battery. Almost %10 per hour.

**Comment by saidinesh5** [comment]
Closing the issue as the battery drain has been reported to be due to cellular data being on, and the 3G and LTE issues have been caused because of wrong network
