### ISSUE TITLE
Sometimes, homescreen is frozen while waking up

### ISSUE THREAD

**Issue by isgursoy** [CancroSailors/droid-config-cancro#9]
I noticed that it is okay if you use volume keys to wake up. Lock button and dt2w are problematic.
It always freezes if an earphone is plugged.

**Comment by saidinesh5** [comment]
Does this happen even with the new patch i mentioned?
Also the device tends to be not locked if the proximity sensor is covered, in order  to prevent accidental wake ups. 

Btw. i haven't enabled volume keys to wake up. Not sure how that's working

**Comment by isgursoy** [comment]
Trying

**Comment by isgursoy** [comment]
Does not work.
